export const environment = {
  production: true,
  supabaseUrl: 'https://slbespgvkdhwxlqgbuvo.supabase.co',
  supabaseKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYmVzcGd2a2Rod3hscWdidXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjczNzMyOTIsImV4cCI6MjA0Mjk0OTI5Mn0.lI0_zf6JUMBGCkXp5YPd7T4BrdiwfAai-oAL7w6EpmA',
  serviceRoleKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYmVzcGd2a2Rod3hscWdidXZvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNzM3MzI5MiwiZXhwIjoyMDQyOTQ5MjkyfQ.pyzvK04lyBwCadZPJ0I1FkPMZkxwef-9T3YEwzKPydQ'
};
